#title: "Data Science and Research Portfolio"
description: "Data Science and Research Portfolio"
theme: jekyll-theme-cayman
show_downloads: false

# Enable kramdown + MathJax for LaTeX equations
markdown: kramdown
kramdown:
  math_engine: mathjax
